# @package _global_
testset:
  name: flyingthings3d
  root_dir: /mnt/flyingthings3d_subset_prep
  split: val
  n_workers: 8
  batch_size: 6

  n_points: 8192
  max_depth: 35.0
  pass_name: clean
  with_pc: true
  with_image: false

  augmentation:
    enabled: false
